@extends('frontend.layouts.master')


@section('content')
    <!-- Content -->
<style>
    div {
  text-align: justify;
  text-justify: inter-word;
}
</style>
<div class="page-content bg-white">
<div class="page-banner ovbl-dark" style="background-image:url({{ asset('images/banner/banner2.jpg')}}')}});">
    <div class="container">
        <div class="page-banner-entry">
          <br/>
          <br/>

 </div>
    </div>
</div>
<!-- Breadcrumb row -->
<div class="breadcrumb-row">
<div class="container">
<ul class="list-inline">
  <li><a href="{{route('home')}}">Home</a></li>
  <li>Privacy Policy</li>
</ul>
</div>
</div>

        <!-- Page Heading Box END ==== -->
        <!-- Page Content Box ==== -->
        <div class="content-block">
            <!-- About Us ==== -->

            <!-- About Us END ==== -->
            <!-- Our Story ==== -->
            <div class="section-area bg-gray section-sp1 our-story">
                <div class="container">
                    <div class="row align-items-center d-flex">


                        <div class="container">
                            <strong style="color: #17365D; font-size:18px;">Global Skills Development Agency Privacy Policy</strong><br> Last updated: February 16, 2022</strong>
                            <br><br>
                            <p>This privacy policy describes our policies and procedures on the collection, use and
                                disclosure of your information when you use the service and tells you about your privacy
                                rights and how the law protects you.<br><br>
                                We use Your Personal data to provide and improve the Service. By using the Service, You
                                agree to the collection and use of information in accordance with this Privacy Policy. This
                                Privacy Policy has been created with the help of the Privacy Policy Template.
                            </p>
                            <h5 style="text-decoration: underline; color: #17365D">Interpretation and Definitions</h5>
                            <h6 style="color: #6E97C9;">Interpretation</h6>
                            <p>The words of which the initial letter is capitalized have meanings defined under the
                                following conditions. The following definitions shall have the same meaning regardless of
                                whether they appear in singular or in plural.</p>
                            <h6 style="color: #6E97C9;">Definitions</h6>
                            <p>For the purposes of this Privacy Policy:</p>
                            <div style="margin-left: 40px;">
                                <p> <strong>Account</strong> means a unique account created for you to access our Service or
                                    parts of our Service.<br>
                                    <strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in
                                    this Agreement) refers to Global Skills Development Agency, 5th Floor, Hayat Rose, 16
                                    Bashundhara Rd, Dhaka, Bangladesh.<br>
                                    <strong>Cookies</strong>
                                    are small files that are placed on your computer, mobile device or any other device by a
                                    website, containing the details of your browsing history on that website among its many
                                    uses.<br>
                                    <strong>Country</strong>
                                    refers to: Bangladesh<br>
                                    <strong>Device</strong>
                                    means any device that can access the Service such as a computer, a cellphone or a
                                    digital tablet.<br>
                                    <strong>Personal Data</strong>
                                    is any information that relates to an identified or identifiable individual.<br>
                                    <strong>Service</strong>
                                    refers to the Website.<br>
                                    <strong>Service Provider</strong>
                                    means any natural or legal person who processes the data on behalf of the Company. It
                                    refers to third-party companies or individuals employed by the Company to facilitate the
                                    Service, to provide the Service on behalf of the Company, to perform services related to
                                    the Service or to assist the Company in analyzing how the Service is used.<br>
                                    <strong>Usage Data</strong>
                                    refers to data collected automatically, either generated by the use of the Service or
                                    from the Service infrastructure itself (for example, the duration of a page visit).<br>
                                    <strong>Website</strong>
                                    refers to Global Skills Development Agency, accessible from www.globalskills.com.bd<br>
                                    <strong>You</strong>
                                    means the individual accessing or using the Service, or the company, or other legal
                                    entity on behalf of which such individual is accessing or using the Service, as
                                    applicable.<br>
                                </p>
                            </div>
                            <h5 style="text-decoration: underline; color: #17365D;">Collecting and Using Your Personal Data
                            </h5>
                            <h6 style="color: #4F81BD;">Types of Data Collected</h6>
                            <strong style="color: #4F81BD;">Personal Data</strong>
                            <p>While using our service, we may ask you to provide us with certain personally identifiable
                                information that can be used to contact or identify you. Personally identifiable information
                                may include, but is not limited to:</p>
                            <div style="margin-left: 40px;">
                                <p>Email address <br>First name and last name<br>Phone number<br>Address, State, Province,
                                    ZIP/Postal code, City<br>
                                    Designation<br>
                                    Company Name<br>
                                    Usage Data</p>
                            </div>
                            <strong style="color: #4F81BD;">Usage Data</strong>
                            <p>Usage Data is collected automatically when using the Service.</p>
                            <p>Usage Data may include information such as your device's Internet Protocol address (e.g. IP
                                address), browser type, browser version, the pages of our Service that you visit, the time
                                and date of your visit, the time spent on those pages, unique device identifiers and other
                                diagnostic data.</p>
                            <p>When you access the service by or through a mobile device, we may collect certain information
                                automatically, including, but not limited to, the type of mobile device you use, your mobile
                                device unique id, the ip address of your mobile device, your mobile operating system, the
                                type of mobile internet browser you use, unique device identifiers and other diagnostic
                                data.</p>
                            <p>We may also collect information that Your browser sends whenever You visit our Service or
                                when You access the Service by or through a mobile device.</p>
                            <strong style="color: #4F81BD;">Tracking Technologies and Cookies</strong>
                            <p>We use Cookies and similar tracking technologies to track the activity on Our Service and
                                store certain information. Tracking technologies used are beacons, tags, and scripts to
                                collect and track information and to improve and analyze Our Service. The technologies We
                                use may include:</p>
                            <div style="margin-left: 40px;">


                                <ul>
                                    <li> <strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on
                                        your Device. You can instruct your browser to refuse all Cookies or to indicate when
                                        a Cookie is being sent. However, if you do not accept Cookies, you may not be able
                                        to use some parts of our Service. Unless you have adjusted Your browser setting so
                                        that it will refuse Cookies, our Service may use Cookies.</li>
                                    <li> <strong>Flash Cookies.</strong> Certain features of our Service may use local
                                        stored objects (or Flash Cookies) to collect and store information about your
                                        preferences or your activity on our Service. Flash Cookies are not managed by the
                                        same browser settings as those used for Browser Cookies. For more information on how
                                        you can delete Flash Cookies, please read "Where can I change the settings for
                                        disabling, or deleting local shared objects?" available at
                                        https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_
                                    </li>
                                    <li> <strong>Web Beacons.</strong> Certain sections of our Service and our emails may
                                        contain small electronic files known as web beacons (also referred to as clear gifs,
                                        pixel tags, and single-pixel gifs) that permit the Company, for example, to count
                                        users who have visited those pages or opened an email and for other related website
                                        statistics (for example, recording the popularity of a certain section and verifying
                                        system and server integrity).</li>
                                </ul>
                            </div>
                            <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on your personal
                                computer or mobile device when you go offline, while Session Cookies are deleted as soon as
                                you close your web browser.</p>
                            <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
                            <div style="margin-left: 40px;">
                                <strong>Necessary / Essential Cookies</strong>
                                <p>Type: Session Cookies<br>
                                    Administered by: Us<br>
                                    Purpose: These Cookies are essential to provide you with services available through the
                                    Website and to enable you to use some of its features. They help to authenticate users
                                    and prevent fraudulent use of user accounts. Without these Cookies, the services that
                                    you have asked for cannot be provided, and we only use these Cookies to provide you with
                                    those services.<br>
                                    <strong>Cookies Policy / Notice Acceptance Cookies</strong><br>
                                    Type: Persistent Cookies<br>
                                    Administered by: Us<br>
                                    Purpose: These Cookies identify if users have accepted the use of cookies on the
                                    Website.<br>
                                    <strong>Functionality Cookies</strong><br>
                                    Type: Persistent Cookies<br>
                                    Administered by: Us<br>
                                    Purpose: These Cookies allow us to remember choices you make when you use the Website,
                                    such as remembering your login details or language preference. The purpose of these
                                    Cookies is to provide you with a more personal experience and to avoid you having to
                                    re-enter your preferences every time you use the Website.
                                </p>
                            </div>



                            <p>For more information about the cookies we use and your choices regarding cookies, please
                                visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>
                            <h6 style="color: #4F81BD;">Use of Your Personal Data</h6>
                            <p>The Company may use Personal Data for the following purposes:</p>
                            <div style="margin-left: 40px;">
                                <p> <strong>To provide and maintain our Service,</strong> including to monitor the usage of
                                    our Service.
                                    <br>
                                    <strong>To manage Your Account:</strong>
                                    to manage Your registration as a user of the Service. The Personal Data you provide can
                                    give you access to different functionalities of the Service that are available to you as
                                    a registered user.<br>
                                    <strong>For the performance of a contract:</strong>
                                    the development, compliance and undertaking of the purchase contract for the products,
                                    items or services you have purchased or of any other contract with us through the
                                    Service.<br>
                                    <strong>To contact You:</strong>
                                    To contact you by email, telephone calls, SMS, or other equivalent forms of electronic
                                    communication, such as a mobile application's push notifications regarding updates or
                                    informative communications related to the functionalities, products or contracted
                                    services, including the security updates, when necessary or reasonable for their
                                    implementation.<br>
                                    <strong>To provide you</strong>
                                    with news, special offers and general information about other goods, services and events
                                    which we offer that are similar to those that you have already purchased or enquired
                                    about unless you have opted not to receive such information.<br>
                                    <strong>To manage your requests:</strong>
                                    To attend and manage your requests to us.<br>
                                    <strong>For business transfers:</strong>
                                    We may use your information to evaluate or conduct a merger, divestiture, restructuring,
                                    reorganization, dissolution, or other sale or transfer of some or all of our assets,
                                    whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding,
                                    in which Personal Data held by us about our Service users is among the assets
                                    transferred.<br>
                                    <strong>For other purposes:</strong>
                                    We may use your information for other purposes, such as data analysis, identifying usage
                                    trends, determining the effectiveness of our promotional campaigns and to evaluate and
                                    improve our service, products, services, marketing and your experience.


                                </p>
                            </div>
                            <p>We may share Your personal information in the following situations:</p>
                            <div style="margin-left: 40px;">
                                <ul>
                                    <li><strong>With Service Providers:</strong> We may share your personal information with
                                        Service Providers to monitor and analyze the use of our Service, to contact you.
                                    </li>
                                    <li><strong>For business transfers:</strong> We may share or transfer your personal
                                        information in connection with, or during negotiations of, any merger, sale of
                                        company assets, financing, or acquisition of all or a portion of our business to
                                        another company.</li>
                                    <li><strong>With Affiliates:</strong> We may share your information with our affiliates,
                                        in which case we will require those affiliates to honor this Privacy Policy.
                                        Affiliates include our associate companies and any other subsidiaries, joint venture
                                        partners or other companies that we control or that are under common control with
                                        us.</li>
                                    <li><strong>With business partners:</strong> We may share your information with our
                                        business partners to book your exams, certifications, trainings or offer you certain
                                        products, services or promotions. </li>
                                    <li><strong>With other users:</strong> when you share personal information or otherwise
                                        interact in the public areas with other users, such information may be viewed by all
                                        users and may be publicly distributed outside.</li>
                                    <li><strong>With your consent:</strong> We may disclose your personal information for
                                        any other purpose with your consent.</li>
                                </ul>
                            </div>
                            <h6 style="color: #4F81BD;">Retention of Your Personal Data</h6>
                            <p>The company will retain your Personal Data only for as long as is necessary for the purposes
                                set out in this Privacy Policy. We will retain and use your Personal Data to the extent
                                necessary to comply with our legal obligations (for example, if we are required to retain
                                your data to comply with applicable laws), resolve disputes, and enforce our legal
                                agreements and policies.</p>
                            <p>The company will also retain Usage Data for internal analysis purposes. Usage Data is
                                generally retained for a shorter period of time, except when this data is used to strengthen
                                the security or to improve the functionality of our service, or we are legally obligated to
                                retain this data for longer time periods.</p>
                            <h6 style="color: #4F81BD;">Transfer of Your Personal Data</h6>
                            <p>Your information, including Personal Data, is processed at the company's operating offices
                                and in any other places where the parties involved in the processing are located. It means
                                that this information may be transferred to — and maintained on — computers located outside
                                of your state, province, country or other governmental jurisdiction where the data
                                protection laws may differ than those from your jurisdiction.</p>
                            <p>Your consent to this Privacy Policy followed by your submission of such information
                                represents your agreement to that transfer.</p>
                            <p>The Company will take all steps reasonably necessary to ensure that your data is treated
                                securely and in accordance with this Privacy Policy and no transfer of your Personal Data
                                will take place to an organization or a country unless there are adequate controls in place
                                including the security of your data and other personal information.</p>
                            <h6 style="color: #4F81BD;">Disclosure of Your Personal Data</h6>
                            <strong style="color: #4F81BD;">Business Transactions</strong>
                            <p>If the company is involved in a merger, acquisition or asset sale, your Personal Data may be
                                transferred. We will provide notice before your Personal Data is transferred and becomes
                                subject to a different Privacy Policy.</p>
                            <strong style="color: #4F81BD;">Law enforcement</strong>
                            <p>Under certain circumstances, the company may be required to disclose your Personal Data if
                                required to do so by law or in response to valid requests by public authorities (e.g. a
                                court or a government agency).</p>
                            <strong style="color: #4F81BD;">Other legal requirements</strong>
                            <p>The company may disclose your Personal Data in the good faith belief that such action is
                                necessary to:</p>
                            <div style="margin-left: 40px;">
                                <ul>
                                    <li>Comply with a legal obligation</li>
                                    <li>Protect and defend the rights or property of the company</li>
                                    <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                                    <li>Protect the personal safety of Users of the Service or the public</li>
                                    <li>Protect against legal liability</li>
                                </ul>
                            </div>


                            <h6 style="color: #4F81BD;">Security of Your Personal Data</h6>
                            <p>The security of Your Personal Data is important to Us, but remember that no method of
                                transmission over the Internet, or method of electronic storage is 100% secure. While we
                                strive to use commercially acceptable means to protect your Personal Data, we cannot
                                guarantee its absolute security.</p>
                                <h5 style="text-decoration:underline; color: #17365D;">Links to Other Websites</h5>
                                <p>Our service may contain links to other websites that are not operated by us. If you click on
                                    a third party link, you will be directed to that third party's site. We strongly advise you
                                    to review the privacy policy of every site you visit.</p>
                                <p>We have no control over and assume no responsibility for the content, privacy policies or
                                    practices of any third party sites or services.</p>
                                <h5 style="text-decoration:underline; color: #17365D;">Changes to this Privacy Policy</h5>
                                <p>We may update our Privacy Policy from time to time. We will notify you of any changes by
                                    posting the new Privacy Policy on this page.</p>
                                <p>We will let you know via email and/or a prominent notice on our service, prior to the change
                                    becoming effective and update the "last updated" date at the top of this Privacy Policy.</p>
                                <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this
                                    Privacy Policy are effective when they are posted on this page.</p>

                                <h5 style="text-decoration:underline; color: #17365D;">Contact Us</h5>

                                <p>If you have any questions about this Privacy Policy, You can contact us:</p>
                                <div style="margin-left: 40px;">
                                    <p>By visiting this page on our website: <a href="https://www.globalskills.com.bd/register">https://www.globalskills.com.bd/register</a> <br>
                                        By phone number: +8801766343434 <br>
                                        By email address: <a href="mailto:info@globalskills.com.bd">info@globalskills.com.bd</a>
                                    </p>
                                </div>


                            </div>
                        </div>
                    </div>
                    <!-- Our Story END ==== -->
                    <!-- Our Status ==== -->

                    <!-- Our Status END ==== -->
                    <!-- About Content ==== -->

                    <!-- About Content END ==== -->
                    <!-- Testimonials ==== -->

                    <!-- Testimonials END ==== -->
                </div>
                <!-- Page Content Box END ==== -->
            </div>
          </div>
            <br>
            <!-- Inner Content Box END ==== -->
            <!-- Content END-->
@endsection
